### ISSUE TITLE
建議

### ISSUE THREAD

**Issue by hatelove** [TsungHsun/Day2Homework#1]
1. 設計時切勿把不同的東西共用同一個 variable, 只為了避免重複宣告 variable。重新 assign/override variable 的值，基本上就是比較不好的設計，也會讓 variable 生命週期變長，不論在 gc 回收或是維護上的 side effect 都會造成衍生問題。
2. 要避免透過集合的index來賦予特定意義，例如 index 0 代表 第一集。因為光看該 array or List, 從程式碼上是無法直接理解這件事。可以採用 HashSet or Dictionary 處理。

其他部分，這個 homework 做得很好，重構設計上也很用心。可以再多瞭解一些資料結構使用上的差異，以便挑選最合適使用場景的資料結構來存取資料。

測試上還有兩種邊界值的 test case, 例如: {1, 100, 100, 100, 100} 或 {1000,1,1,1,1} 如果很在乎 algorithm 的 performance, 可以想辦法讓迴圈的執行次數降到最低。

**Comment by TsungHsun** [comment]
1. 我本來一直天真的以為那樣的寫法能重複使用變數, 不用一直宣告新的記憶體空間比較不會浪費記憶體, 也不用等gc回收, 原來這是一個糟糕的習慣, 以後會把這壞習慣改掉 .
2. 用index去賦予特定意義確實是不好的設計, 一開始還沒仔細考慮要用哪種結構處理這個資料就先隨便用了, 結果只沉浸在紅燈變綠燈的快感, 最後重構時也忘了這一塊, 是個疏忽 .

已依照建議再調整了一下程式, 也把計算的效能考慮進去, 真的很感謝這麼有耐心的Code Review, 謝謝 .
